/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingSkillTestRouteImport } from './routes/onboarding/skill-test'
import { Route as OnboardingFreelancerProfileRouteImport } from './routes/onboarding/freelancer-profile'
import { Route as OnboardingAadhaarRouteImport } from './routes/onboarding/aadhaar'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthRoleSelectRouteImport } from './routes/auth/role-select'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppWalletRouteImport } from './routes/_app/wallet'
import { Route as AppTypingArenaRouteImport } from './routes/_app/typing-arena'
import { Route as AppTrialsRouteImport } from './routes/_app/trials'
import { Route as AppTeamFinderRouteImport } from './routes/_app/team-finder'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppMessagesRouteImport } from './routes/_app/messages'
import { Route as AppMeetingsRouteImport } from './routes/_app/meetings'
import { Route as AppLeaderboardRouteImport } from './routes/_app/leaderboard'
import { Route as AppJobsRouteImport } from './routes/_app/jobs'
import { Route as AppFreelancersRouteImport } from './routes/_app/freelancers'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppTypingArenaHistoryRouteImport } from './routes/_app/typing-arena.history'
import { Route as AppJobsNewRouteImport } from './routes/_app/jobs.new'
import { Route as AppJobsJobIdRouteImport } from './routes/_app/jobs.$jobId'
import { Route as AppFreelancersUserIdRouteImport } from './routes/_app/freelancers.$userId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSkillTestRoute = OnboardingSkillTestRouteImport.update({
  id: '/onboarding/skill-test',
  path: '/onboarding/skill-test',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingFreelancerProfileRoute =
  OnboardingFreelancerProfileRouteImport.update({
    id: '/onboarding/freelancer-profile',
    path: '/onboarding/freelancer-profile',
    getParentRoute: () => rootRouteImport,
  } as any)
const OnboardingAadhaarRoute = OnboardingAadhaarRouteImport.update({
  id: '/onboarding/aadhaar',
  path: '/onboarding/aadhaar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoleSelectRoute = AuthRoleSelectRouteImport.update({
  id: '/auth/role-select',
  path: '/auth/role-select',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppTypingArenaRoute = AppTypingArenaRouteImport.update({
  id: '/typing-arena',
  path: '/typing-arena',
  getParentRoute: () => AppRoute,
} as any)
const AppTrialsRoute = AppTrialsRouteImport.update({
  id: '/trials',
  path: '/trials',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamFinderRoute = AppTeamFinderRouteImport.update({
  id: '/team-finder',
  path: '/team-finder',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsRoute = AppMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppFreelancersRoute = AppFreelancersRouteImport.update({
  id: '/freelancers',
  path: '/freelancers',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppTypingArenaHistoryRoute = AppTypingArenaHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppTypingArenaRoute,
} as any)
const AppJobsNewRoute = AppJobsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppJobsRoute,
} as any)
const AppJobsJobIdRoute = AppJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => AppJobsRoute,
} as any)
const AppFreelancersUserIdRoute = AppFreelancersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppFreelancersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AppAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/freelancers': typeof AppFreelancersRouteWithChildren
  '/jobs': typeof AppJobsRouteWithChildren
  '/leaderboard': typeof AppLeaderboardRoute
  '/meetings': typeof AppMeetingsRoute
  '/messages': typeof AppMessagesRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/team-finder': typeof AppTeamFinderRoute
  '/trials': typeof AppTrialsRoute
  '/typing-arena': typeof AppTypingArenaRouteWithChildren
  '/wallet': typeof AppWalletRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/role-select': typeof AuthRoleSelectRoute
  '/auth/signup': typeof AuthSignupRoute
  '/onboarding/aadhaar': typeof OnboardingAadhaarRoute
  '/onboarding/freelancer-profile': typeof OnboardingFreelancerProfileRoute
  '/onboarding/skill-test': typeof OnboardingSkillTestRoute
  '/freelancers/$userId': typeof AppFreelancersUserIdRoute
  '/jobs/$jobId': typeof AppJobsJobIdRoute
  '/jobs/new': typeof AppJobsNewRoute
  '/typing-arena/history': typeof AppTypingArenaHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AppAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/freelancers': typeof AppFreelancersRouteWithChildren
  '/jobs': typeof AppJobsRouteWithChildren
  '/leaderboard': typeof AppLeaderboardRoute
  '/meetings': typeof AppMeetingsRoute
  '/messages': typeof AppMessagesRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/team-finder': typeof AppTeamFinderRoute
  '/trials': typeof AppTrialsRoute
  '/typing-arena': typeof AppTypingArenaRouteWithChildren
  '/wallet': typeof AppWalletRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/role-select': typeof AuthRoleSelectRoute
  '/auth/signup': typeof AuthSignupRoute
  '/onboarding/aadhaar': typeof OnboardingAadhaarRoute
  '/onboarding/freelancer-profile': typeof OnboardingFreelancerProfileRoute
  '/onboarding/skill-test': typeof OnboardingSkillTestRoute
  '/freelancers/$userId': typeof AppFreelancersUserIdRoute
  '/jobs/$jobId': typeof AppJobsJobIdRoute
  '/jobs/new': typeof AppJobsNewRoute
  '/typing-arena/history': typeof AppTypingArenaHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/admin': typeof AppAdminRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/freelancers': typeof AppFreelancersRouteWithChildren
  '/_app/jobs': typeof AppJobsRouteWithChildren
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/meetings': typeof AppMeetingsRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/team-finder': typeof AppTeamFinderRoute
  '/_app/trials': typeof AppTrialsRoute
  '/_app/typing-arena': typeof AppTypingArenaRouteWithChildren
  '/_app/wallet': typeof AppWalletRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/role-select': typeof AuthRoleSelectRoute
  '/auth/signup': typeof AuthSignupRoute
  '/onboarding/aadhaar': typeof OnboardingAadhaarRoute
  '/onboarding/freelancer-profile': typeof OnboardingFreelancerProfileRoute
  '/onboarding/skill-test': typeof OnboardingSkillTestRoute
  '/_app/freelancers/$userId': typeof AppFreelancersUserIdRoute
  '/_app/jobs/$jobId': typeof AppJobsJobIdRoute
  '/_app/jobs/new': typeof AppJobsNewRoute
  '/_app/typing-arena/history': typeof AppTypingArenaHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/freelancers'
    | '/jobs'
    | '/leaderboard'
    | '/meetings'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/team-finder'
    | '/trials'
    | '/typing-arena'
    | '/wallet'
    | '/auth/login'
    | '/auth/role-select'
    | '/auth/signup'
    | '/onboarding/aadhaar'
    | '/onboarding/freelancer-profile'
    | '/onboarding/skill-test'
    | '/freelancers/$userId'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/typing-arena/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/freelancers'
    | '/jobs'
    | '/leaderboard'
    | '/meetings'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/team-finder'
    | '/trials'
    | '/typing-arena'
    | '/wallet'
    | '/auth/login'
    | '/auth/role-select'
    | '/auth/signup'
    | '/onboarding/aadhaar'
    | '/onboarding/freelancer-profile'
    | '/onboarding/skill-test'
    | '/freelancers/$userId'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/typing-arena/history'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/freelancers'
    | '/_app/jobs'
    | '/_app/leaderboard'
    | '/_app/meetings'
    | '/_app/messages'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/team-finder'
    | '/_app/trials'
    | '/_app/typing-arena'
    | '/_app/wallet'
    | '/auth/login'
    | '/auth/role-select'
    | '/auth/signup'
    | '/onboarding/aadhaar'
    | '/onboarding/freelancer-profile'
    | '/onboarding/skill-test'
    | '/_app/freelancers/$userId'
    | '/_app/jobs/$jobId'
    | '/_app/jobs/new'
    | '/_app/typing-arena/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRoleSelectRoute: typeof AuthRoleSelectRoute
  AuthSignupRoute: typeof AuthSignupRoute
  OnboardingAadhaarRoute: typeof OnboardingAadhaarRoute
  OnboardingFreelancerProfileRoute: typeof OnboardingFreelancerProfileRoute
  OnboardingSkillTestRoute: typeof OnboardingSkillTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/skill-test': {
      id: '/onboarding/skill-test'
      path: '/onboarding/skill-test'
      fullPath: '/onboarding/skill-test'
      preLoaderRoute: typeof OnboardingSkillTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/freelancer-profile': {
      id: '/onboarding/freelancer-profile'
      path: '/onboarding/freelancer-profile'
      fullPath: '/onboarding/freelancer-profile'
      preLoaderRoute: typeof OnboardingFreelancerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/aadhaar': {
      id: '/onboarding/aadhaar'
      path: '/onboarding/aadhaar'
      fullPath: '/onboarding/aadhaar'
      preLoaderRoute: typeof OnboardingAadhaarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/role-select': {
      id: '/auth/role-select'
      path: '/auth/role-select'
      fullPath: '/auth/role-select'
      preLoaderRoute: typeof AuthRoleSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/typing-arena': {
      id: '/_app/typing-arena'
      path: '/typing-arena'
      fullPath: '/typing-arena'
      preLoaderRoute: typeof AppTypingArenaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trials': {
      id: '/_app/trials'
      path: '/trials'
      fullPath: '/trials'
      preLoaderRoute: typeof AppTrialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team-finder': {
      id: '/_app/team-finder'
      path: '/team-finder'
      fullPath: '/team-finder'
      preLoaderRoute: typeof AppTeamFinderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meetings': {
      id: '/_app/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AppMeetingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/freelancers': {
      id: '/_app/freelancers'
      path: '/freelancers'
      fullPath: '/freelancers'
      preLoaderRoute: typeof AppFreelancersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/typing-arena/history': {
      id: '/_app/typing-arena/history'
      path: '/history'
      fullPath: '/typing-arena/history'
      preLoaderRoute: typeof AppTypingArenaHistoryRouteImport
      parentRoute: typeof AppTypingArenaRoute
    }
    '/_app/jobs/new': {
      id: '/_app/jobs/new'
      path: '/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof AppJobsNewRouteImport
      parentRoute: typeof AppJobsRoute
    }
    '/_app/jobs/$jobId': {
      id: '/_app/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AppJobsJobIdRouteImport
      parentRoute: typeof AppJobsRoute
    }
    '/_app/freelancers/$userId': {
      id: '/_app/freelancers/$userId'
      path: '/$userId'
      fullPath: '/freelancers/$userId'
      preLoaderRoute: typeof AppFreelancersUserIdRouteImport
      parentRoute: typeof AppFreelancersRoute
    }
  }
}

interface AppFreelancersRouteChildren {
  AppFreelancersUserIdRoute: typeof AppFreelancersUserIdRoute
}

const AppFreelancersRouteChildren: AppFreelancersRouteChildren = {
  AppFreelancersUserIdRoute: AppFreelancersUserIdRoute,
}

const AppFreelancersRouteWithChildren = AppFreelancersRoute._addFileChildren(
  AppFreelancersRouteChildren,
)

interface AppJobsRouteChildren {
  AppJobsJobIdRoute: typeof AppJobsJobIdRoute
  AppJobsNewRoute: typeof AppJobsNewRoute
}

const AppJobsRouteChildren: AppJobsRouteChildren = {
  AppJobsJobIdRoute: AppJobsJobIdRoute,
  AppJobsNewRoute: AppJobsNewRoute,
}

const AppJobsRouteWithChildren =
  AppJobsRoute._addFileChildren(AppJobsRouteChildren)

interface AppTypingArenaRouteChildren {
  AppTypingArenaHistoryRoute: typeof AppTypingArenaHistoryRoute
}

const AppTypingArenaRouteChildren: AppTypingArenaRouteChildren = {
  AppTypingArenaHistoryRoute: AppTypingArenaHistoryRoute,
}

const AppTypingArenaRouteWithChildren = AppTypingArenaRoute._addFileChildren(
  AppTypingArenaRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFreelancersRoute: typeof AppFreelancersRouteWithChildren
  AppJobsRoute: typeof AppJobsRouteWithChildren
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppMeetingsRoute: typeof AppMeetingsRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamFinderRoute: typeof AppTeamFinderRoute
  AppTrialsRoute: typeof AppTrialsRoute
  AppTypingArenaRoute: typeof AppTypingArenaRouteWithChildren
  AppWalletRoute: typeof AppWalletRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFreelancersRoute: AppFreelancersRouteWithChildren,
  AppJobsRoute: AppJobsRouteWithChildren,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppMeetingsRoute: AppMeetingsRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamFinderRoute: AppTeamFinderRoute,
  AppTrialsRoute: AppTrialsRoute,
  AppTypingArenaRoute: AppTypingArenaRouteWithChildren,
  AppWalletRoute: AppWalletRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRoleSelectRoute: AuthRoleSelectRoute,
  AuthSignupRoute: AuthSignupRoute,
  OnboardingAadhaarRoute: OnboardingAadhaarRoute,
  OnboardingFreelancerProfileRoute: OnboardingFreelancerProfileRoute,
  OnboardingSkillTestRoute: OnboardingSkillTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
